repos:
  - repo: https://github.com/cachix/pre-commit-hooks.nix
    rev: v1.0.1
    hooks:
      - id: alejandra
      - id: statix
      - id: deadnix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
